# Generated by Django 3.1.2 on 2021-10-04 06:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0003_watch'),
    ]

    operations = [
        migrations.AddField(
            model_name='watch',
            name='cik',
            field=models.CharField(default='a', max_length=255, verbose_name='CIKコード'),
            preserve_default=False,
        ),
    ]
