# Generated by Django 3.1.2 on 2021-10-04 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0004_watch_cik'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='cik',
            field=models.CharField(default='aaa', max_length=255, verbose_name='CIKコード'),
            preserve_default=False,
        ),
    ]
