# Generated by Django 3.1.2 on 2021-10-04 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0005_companylist_cik'),
    ]

    operations = [
        migrations.AddField(
            model_name='companylist',
            name='exchange',
            field=models.CharField(default='qq', max_length=255, verbose_name='取引市場'),
            preserve_default=False,
        ),
    ]
