# Generated by Django 3.1.2 on 2021-10-04 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0006_companylist_exchange'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companylist',
            name='exchange',
            field=models.CharField(max_length=255, null=True, verbose_name='取引市場'),
        ),
    ]
