# Generated by Django 3.1.2 on 2021-10-15 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0007_auto_20211004_0846'),
    ]

    operations = [
        migrations.CreateModel(
            name='Accounting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, verbose_name='企業名')),
                ('accounting_type', models.CharField(max_length=255, verbose_name='決算種類')),
                ('revenue', models.BigIntegerField(verbose_name='売上')),
                ('operating_income', models.BigIntegerField(verbose_name='営業利益')),
                ('net_income', models.BigIntegerField(verbose_name='純利益')),
                ('earnings_per_share', models.FloatField(verbose_name='EPS')),
                ('period', models.CharField(max_length=255, verbose_name='決算種類')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '決算数値',
            },
        ),
    ]
