# Generated by Django 3.1.2 on 2021-10-15 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0008_accounting'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounting',
            name='earnings_per_share',
            field=models.FloatField(null=True, verbose_name='EPS'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='net_income',
            field=models.BigIntegerField(null=True, verbose_name='純利益'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='operating_income',
            field=models.BigIntegerField(null=True, verbose_name='営業利益'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='period',
            field=models.CharField(max_length=255, verbose_name='決算期間'),
        ),
        migrations.AlterField(
            model_name='accounting',
            name='revenue',
            field=models.BigIntegerField(null=True, verbose_name='売上'),
        ),
    ]
