# Generated by Django 3.1.2 on 2021-10-17 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0009_auto_20211015_0347'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='cik',
            field=models.CharField(default=0, max_length=255, verbose_name='CIKコード'),
            preserve_default=False,
        ),
    ]
