# Generated by Django 3.1.2 on 2021-10-18 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0010_accounting_cik'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounting',
            name='finaicial_year',
            field=models.CharField(default='-', max_length=255, verbose_name='会計年度'),
        ),
        migrations.AddField(
            model_name='accounting',
            name='fiscal_period',
            field=models.CharField(default='-', max_length=255, verbose_name='会計期間'),
        ),
    ]
