# Generated by Django 3.1.2 on 2021-10-18 07:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('company_info', '0011_auto_20211018_0520'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounting',
            name='finaicial_year',
        ),
    ]
